services:
  order-db:
    container_name: postgresql-order
    image: postgres:latest
    environment:
      POSTGRES_DB: order-db
      POSTGRES_USER: order-postgres-user
      POSTGRES_PASSWORD: order-postgres-pwd
    ports:
      - 5435:5432
    volumes:
      - /var/lib/postgres
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge