services:
  customer-db:
    container_name: postgresql-customer
    image: postgres:latest
    environment:
      POSTGRES_DB: customer-db
      POSTGRES_USER: customer-postgres-user
      POSTGRES_PASSWORD: customer-postgres-pwd
    ports:
      - 5433:5432
    volumes:
      - /var/lib/postgres
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge