services:
  batch-db:
    container_name: postgresql-batch
    image: postgres:latest
    environment:
      POSTGRES_DB: batch-db
      POSTGRES_USER: batch-postgres-user
      POSTGRES_PASSWORD: batch-postgres-pwd
    ports:
      - 5437:5432
    volumes:
      - /var/lib/postgres
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge